//
//  UserLoginInteractor.swift
//  AppleIdLogin
//
//  Created by Emmanuvel Thamel on 3/23/20.
//  Copyright (c) 2020 Creative Software. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AuthenticationServices

protocol UserLoginBusinessLogic
{
    func loginWithAppleId(controller: ASAuthorizationController)
}

protocol UserLoginDataStore
{
    var loggedInUser: UserLogin.AppleIdLogin.Response? { get set }
}

class UserLoginInteractor:NSObject, UserLoginBusinessLogic, UserLoginDataStore
{
    var presenter: UserLoginPresentationLogic?
    var loggedInUser: UserLogin.AppleIdLogin.Response?

    // MARK: SignIn with AppleId

    func loginWithAppleId(controller: ASAuthorizationController)
    {
        controller.delegate = self
        controller.performRequests()
    }
}

extension UserLoginInteractor: ASAuthorizationControllerDelegate {
    func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) {

        switch authorization.credential {
        case let credential as ASAuthorizationAppleIDCredential:
            let response = UserLogin.AppleIdLogin.Response(withCredential: credential)
            loggedInUser = response
            presenter?.presentLoggedInUser(response: response)

        default:
            break
        }
    }

    func authorizationController(controller: ASAuthorizationController, didCompleteWithError error: Error) {
        print("Error: \(error.localizedDescription)")
        // TODO: handle error.
    }
}
