//
//  UserLoginPresenter.swift
//  AppleIdLogin
//
//  Created by Emmanuvel Thamel on 3/23/20.
//  Copyright (c) 2020 Creative Software. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AuthenticationServices

protocol UserLoginPresentationLogic
{
    func presentLoggedInUser(response: UserLogin.AppleIdLogin.Response)
}

class UserLoginPresenter: UserLoginPresentationLogic
{
    weak var viewController: UserLoginDisplayLogic?
    
    // MARK: Present LoggedIn User
    
    func presentLoggedInUser(response: UserLogin.AppleIdLogin.Response) {
        viewController?.displayLoggedInUser()
    }
}
