//
//  UserLoginModels.swift
//  AppleIdLogin
//
//  Created by Emmanuvel Thamel on 3/23/20.
//  Copyright (c) 2020 Creative Software. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AuthenticationServices

enum UserLogin
{
    // MARK: Use cases
    
    enum AppleIdLogin
    {
        struct Response
        {
            let id: String
            let firstName: String
            let lastName: String
            let email: String

            init(withCredential credential: ASAuthorizationAppleIDCredential) {
                self.id = credential.user
                self.firstName = credential.fullName?.givenName ?? ""
                self.lastName = credential.fullName?.familyName ?? ""
                self.email = credential.email ?? ""
            }
        }
        struct ViewModel
        {
            let id: String
            let firstName: String
            let lastName: String
            let email: String
        }
    }
}
