//
//  UserDetailModels.swift
//  AppleIdLogin
//
//  Created by Emmanuvel Thamel on 3/23/20.
//  Copyright (c) 2020 Creative Software. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UserDetail
{
    // MARK: Use cases
    
    enum AppleIdLogin
    {
        struct Request
        {
        }
        struct Response
        {
            let id: String
            let firstName: String
            let lastName: String
            let email: String

            init(loggedInUser: UserLogin.AppleIdLogin.Response) {
                self.id = loggedInUser.id
                self.firstName = loggedInUser.firstName
                self.lastName = loggedInUser.lastName
                self.email = loggedInUser.email
            }
        }
        struct ViewModel
        {
            let id: String
            let firstName: String
            let lastName: String
            let email: String
        }
    }
}
